### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by juhuc** [natanlao/reddit-transfer#1]
Hi, whenever I tried to do
$ python reddit_transfer.py <old_username> <new_username>

I get an error of   File "<fstring>", line 1
    (item.id=)
            ^
SyntaxError: invalid syntax

Can anyone help? Thanks

**Comment by natanlao** [comment]
Hi! Sorry to respond so late, I didn't see this...

The error you're seeing is a little odd to me, since I don't see that line of code in the source tree. Would you mind checking that you have a complete copy of reddit_transfer.py, and update this ticket with the output of `pip freeze` and `python --version`?

Thanks.

**Comment by natanlao** [comment]
I can't reproduce this, and I've rewritten this script substantially, so I'm going to close this issue. If you can reproduce with the latest revision, feel free to reopen.
